### PR TITLE
use lb to build product.iso

### PR DESCRIPTION
**Pull request by a3s7p**
~~caveats:~~

~~- the uefi/grub boot logo is still the debian one (isolinux uses ours)~~
~~- the resulting image is about 50 mb larger than ours~~

^ no longer true

### CODE REVIEW

**Comment by a3s7p** [comment]
@JedMeister @OnGle @Christie018 testing welcome :slightly_smiling_face:

**Comment by JedMeister** [comment]
Cheers mate.

I tried building a bookworm based iso using this and it didn't really work out for me.

The first run I already had a core bookworm built to product.iso. I updated fab, ensured that the decks were mounted and reran `make`. I tried booting the ISO I built on Proxmox. It booted and I got the TurnKey logo, I selected install and I got some install dialog with some errors noted and got stuck in a partitioner loop.

So I went back to TKLDev , commented out di-live (in the common plan) and did a `make clean`, then `TKL_TESTING=y RELEASE=debian/bookworm make` and this time I got a different result. It still booted with the TurnKey logo, but when I selected install it dropped me into a root shell in the live system.

Any ideas/suggestions? Perhaps there is stuff in my env that wasn't in yours (or vice-versa)?

If you could provide details about the env you used when you tested?

**Review by Christie018 — COMMENTED** [review]
After I pull your code changes onto my local tkldev, do I just rerun the make command in the appliance directory to test it?

**Comment by JedMeister** [comment]
@Christie018 - please do test it if you have time/energy. However please note that to apply Anton's changes, you'll need to update/rebuild the `fab` package. So you'll need to (re)build the package yourself. I could upload it somewhere, but perhaps it's better if you build it yourself?! :wink: 

Never having done it before, there will be a learning curve, but with a few hints, I'm guessing you'll be able to work it out. As a overview: To build it yourself on a local TKLDev you'll need to build a [buildroot](https://github.com/turnkeylinux/buildroot), then create a [pool](https://github.com/turnkeylinux/pool). Then clone this source (I put my source in `/turnkey/public/<repo_name>` - i.e. in this case it would be `/turnkey/public/fab` - but that's just my preference), add [Anton's fork](https://github.com/a3s7p/fab/tree/lb) (use the https address) as a `git` remote, check out his `lb` branch, then register the fab source in your pool. Then run `pool-get . fab` to build the package and `apt install ./fab_<version_info>_amd64.deb` to install the updated version.

Hopefully that's enough hints to get you somewhere. Hopefully I've given enough keywords for you to search for additional info. Beyond the TurnKey specific stuff (i.e. fab & pool). Most installed apps should have help available via `man` (e.g. `man git`) or often via a `-h`, `--help` switch or sometimes just `help` command. Between that and google hopefully you can work out the specific required commands. Anymore questions, don't hesitate to ask on slack, any results, post back here.

**Comment by Christie018** [comment]
Okay, so I followed your directions to the best of my ability @JedMeister but got errored out when I tried to build the package. I guess let me make sure I followed the right process before bothering you trying to debug the error code quite yet.
1. I built a buildroot by running the make command in /turnkey/fab/products/core directory.
2. I created a pool with the pool-init /turnkey/fab/products/core/build/root.build command.
3. I cloned antons PR to my local TKLDev with the git clone 
https://github.com/a3s7p/fab.git command.
4. I added Anton's fork as a git remote with the  git remote add upstream https://github.com/a3s7p/fab.git command.
5. I checked out the lb branch with the git checkout lb command.
6. I attempted to register the fab source in the pool I created. I believe I had to  change to the /turnkey/fab/products/core/build/root.build directory first then run the pool-register /turnkey/public/fab command. I think this ran successfully but the next step is where it errored out.
7. I tried running the pool-get . fab command and this is where I got an error message.

I'm going to try running through this one more time bcz  I might've mucked up the local TKLDev environment trying to figure this one out. Please let me know if this is the right steps and I'll try again 👍🏾

**Comment by JedMeister** [comment]
Hey @Christie018 

It sounds like you are so close... But the buildroot isn't a normal core rootfs. It's a special rootfs designed specifically as a build environment for debian packages. Having said that, it may well work with a normal rootfs, but it will be slower (by default the buildroot has a ton of build dependencies pre-installed).

To build a buildroot, check out the readme: https://github.com/turnkeylinux/buildroot#readme. I usually clone that to `/turnkey/buildroot` (i.e. `cd /turnkey; git clone ...`) but it doesn't really matter.

For testing on v17.x (which is what we need to do for now) you don't need to set `RELEASE` (only when you're building alternate versions - e.g. v18.x on v17.x). Once that's completed building, you should find a buildroot here: `/turnkey/fab/buildroots/bullseye`.

IIRC that path is already registered in the default `bullseye` pool (i.e. `/turnkey/fab/pools/bullseye`) but double check:
```
cd pools/bullseye # this should work from anywhere in the filesystem)
pool-init /turnkey/fab/buildroots/bullseye
```

Then (still in the `pools/bullseye` dir) register the source code that you've already cloned and checked out (assuming source is cloned to `turnkey/public` - it looks like you've also cloned it there, but FWIW it shouldn't matter where you've cloned it):
```
pool-register /turnkey/public/fab
pool-get . fab
```
(note the dot - pool-get format is `pool-get <output-dir> <package_name> [<package_name> <...>]` so the dot means "right here").
If you get any error messages, please share.

**Comment by Christie018** [comment]
I'm going to bring this back up at the next TKL meeting.

**Comment by Christie018** [comment]
> I'm going to bring this back up at the next TKL meeting.

Again, I'll bring this up at the next meeting to see it's updates.

**Pull request closed without merging**
